import { NextResponse } from "next/server";

const CATEGORIES: { label: string; keywords: string[] }[] = [
  {
    label: "Sports",
    keywords: [
      "football",
      "soccer",
      "basketball",
      "baseball",
      "cricket",
      "rugby",
      "tennis",
      "golf",
      "cycling",
      "swimmer",
      "swimming",
      "athletics",
      "olympic",
      "nfl",
      "nba",
      "fifa",
      "uefa",
      "championship",
      "league",
      "tournament",
      "club",
      "athlete",
      "boxer",
      "boxing",
      "wrestling",
      "skiing",
      "skating",
      "racing",
      "motorsport",
      "volleyball",
      "hockey",
      "lacrosse",
      "softball",
      "gymnast",
    ],
  },
  {
    label: "Music",
    keywords: [
      "album",
      "song",
      "singer",
      "band",
      "musician",
      "composer",
      "orchestra",
      "symphony",
      "opera",
      "rapper",
      "hip-hop",
      "jazz",
      "blues",
      "rock",
      "pop",
      "discography",
      "record",
      "guitar",
      "piano",
      "vocalist",
      "drummer",
      "conductor",
      "soundtrack",
      "ep",
      "single",
      "genre",
      "punk",
      "metal",
      "folk",
      "indie",
      "reggae",
    ],
  },
  {
    label: "Film",
    keywords: [
      "film",
      "movie",
      "cinema",
      "director",
      "actor",
      "actress",
      "screenplay",
      "documentary",
      "animated",
      "television",
      "tv series",
      "sitcom",
      "drama series",
      "miniseries",
      "streaming",
      "box office",
      "hollywood",
      "bollywood",
    ],
  },
  {
    label: "Politics",
    keywords: [
      "politician",
      "president",
      "prime minister",
      "senator",
      "congressman",
      "parliament",
      "minister",
      "governor",
      "mayor",
      "election",
      "political party",
      "diplomat",
      "ambassador",
      "chancellor",
      "republic",
      "democracy",
      "legislation",
      "constitution",
      "cabinet",
      "congress",
    ],
  },
  {
    label: "Science",
    keywords: [
      "physicist",
      "biologist",
      "chemist",
      "mathematician",
      "astronomer",
      "scientist",
      "researcher",
      "neuroscientist",
      "geologist",
      "ecologist",
      "zoologist",
      "botanist",
      "geneticist",
      "theorem",
      "equation",
      "hypothesis",
      "laboratory",
      "experiment",
      "discovery",
      "nobel",
    ],
  },
  {
    label: "Technology",
    keywords: [
      "software",
      "computer",
      "programmer",
      "engineer",
      "startup",
      "internet",
      "algorithm",
      "artificial intelligence",
      "machine learning",
      "robotics",
      "semiconductor",
      "hardware",
      "app",
      "platform",
      "cybersecurity",
      "database",
      "network",
      "coding",
      "developer",
    ],
  },
  {
    label: "History",
    keywords: [
      "ancient",
      "medieval",
      "century",
      "dynasty",
      "empire",
      "revolution",
      "war",
      "battle",
      "treaty",
      "civilisation",
      "civilization",
      "historical",
      "archaeological",
      "artifact",
      "colony",
      "colonialism",
      "kingdom",
      "reign",
      "pharaoh",
      "samurai",
      "viking",
    ],
  },
  {
    label: "Military",
    keywords: [
      "military",
      "army",
      "navy",
      "air force",
      "general",
      "admiral",
      "colonel",
      "soldier",
      "war",
      "battle",
      "siege",
      "operation",
      "regiment",
      "battalion",
      "brigade",
      "weapon",
      "warship",
      "aircraft carrier",
      "tank",
      "missile",
    ],
  },
  {
    label: "Nature",
    keywords: [
      "species",
      "genus",
      "mammal",
      "bird",
      "fish",
      "insect",
      "reptile",
      "amphibian",
      "plant",
      "tree",
      "flower",
      "fungus",
      "bacteria",
      "virus",
      "ecosystem",
      "habitat",
      "wildlife",
      "conservation",
      "endangered",
      "fossil",
      "dinosaur",
      "marine",
      "coral",
      "primate",
    ],
  },
  {
    label: "Place",
    keywords: [
      "commune",
      "municipality",
      "village",
      "town",
      "city",
      "district",
      "borough",
      "parish",
      "county",
      "province",
      "region",
      "island",
      "peninsula",
      "mountain",
      "river",
      "lake",
      "ocean",
      "sea",
      "bay",
      "cape",
      "valley",
      "desert",
      "forest",
      "national park",
      "landmark",
      "capital",
    ],
  },
  {
    label: "Business",
    keywords: [
      "company",
      "corporation",
      "bank",
      "airline",
      "brand",
      "enterprise",
      "ceo",
      "founded",
      "headquartered",
      "subsidiary",
      "conglomerate",
      "stock",
      "nasdaq",
      "nyse",
      "retail",
      "manufacturer",
      "pharmaceutical",
      "insurance",
      "investment",
      "startup",
      "venture",
    ],
  },
  {
    label: "Arts",
    keywords: [
      "painter",
      "artist",
      "sculptor",
      "architect",
      "photographer",
      "illustrator",
      "designer",
      "ceramicist",
      "printmaker",
      "installation",
      "exhibition",
      "gallery",
      "museum",
      "artwork",
      "painting",
      "sculpture",
      "drawing",
      "sketch",
      "portrait",
      "abstract",
    ],
  },
  {
    label: "Literature",
    keywords: [
      "novelist",
      "author",
      "writer",
      "poet",
      "playwright",
      "essayist",
      "journalist",
      "biography",
      "autobiography",
      "fiction",
      "non-fiction",
      "poem",
      "poetry",
      "short story",
      "novel",
      "book",
      "published",
      "literature",
      "pulitzer",
      "booker",
    ],
  },
  {
    label: "Religion",
    keywords: [
      "religion",
      "church",
      "mosque",
      "temple",
      "cathedral",
      "bishop",
      "priest",
      "monk",
      "imam",
      "rabbi",
      "theology",
      "christian",
      "muslim",
      "hindu",
      "buddhist",
      "jewish",
      "saint",
      "scripture",
      "bible",
      "quran",
      "mythology",
      "god",
      "deity",
      "worship",
    ],
  },
  {
    label: "Medicine",
    keywords: [
      "doctor",
      "physician",
      "surgeon",
      "nurse",
      "medical",
      "disease",
      "syndrome",
      "disorder",
      "treatment",
      "therapy",
      "hospital",
      "anatomy",
      "pharmacology",
      "vaccine",
      "cancer",
      "diabetes",
      "cardiology",
      "neurology",
      "psychiatry",
      "pediatrics",
    ],
  },
  {
    label: "Education",
    keywords: [
      "university",
      "college",
      "school",
      "professor",
      "academic",
      "curriculum",
      "faculty",
      "campus",
      "institute",
      "research",
      "scholarship",
      "degree",
      "phd",
      "student",
      "education",
      "pedagogy",
      "classroom",
    ],
  },
  {
    label: "Food",
    keywords: [
      "food",
      "cuisine",
      "dish",
      "recipe",
      "ingredient",
      "chef",
      "restaurant",
      "cooking",
      "baking",
      "wine",
      "beer",
      "spirits",
      "fruit",
      "vegetable",
      "spice",
      "bread",
      "cheese",
      "meat",
      "seafood",
      "dessert",
      "beverage",
    ],
  },
  {
    label: "Transport",
    keywords: [
      "railway",
      "railroad",
      "locomotive",
      "ship",
      "vessel",
      "aircraft",
      "airport",
      "highway",
      "bridge",
      "tunnel",
      "metro",
      "subway",
      "bus",
      "automobile",
      "car",
      "motorcycle",
      "bicycle",
      "port",
      "canal",
      "road",
    ],
  },
  {
    label: "Culture",
    keywords: [
      "culture",
      "festival",
      "tradition",
      "folklore",
      "mythology",
      "language",
      "ethnic",
      "heritage",
      "ceremony",
      "ritual",
      "custom",
      "tribe",
      "indigenous",
      "dance",
      "theatre",
      "theater",
      "costume",
      "carnival",
    ],
  },
  {
    label: "Person",
    keywords: [
      "born",
      "died",
      "biography",
      "life",
      "career",
      "personal life",
      "early life",
      "childhood",
      "family",
      "married",
      "spouse",
    ],
  },
];

function categorize(title: string, description: string | null): string | null {
  const haystack = `${title} ${description ?? ""}`.toLowerCase();
  let bestLabel: string | null = null;
  let bestScore = 0;

  for (const { label, keywords } of CATEGORIES) {
    const score = keywords.reduce((acc, kw) => acc + (haystack.includes(kw) ? 1 : 0), 0);
    if (score > bestScore) {
      bestScore = score;
      bestLabel = label;
    }
  }

  return bestScore > 0 ? bestLabel : null;
}

export async function GET() {
  try {
    // Fetch 10 random articles in parallel
    const fetches = Array.from({ length: 10 }, () =>
      fetch("https://en.wikipedia.org/api/rest_v1/page/random/summary", {
        headers: { "Api-User-Agent": "wikipedia-feed/1.0" },
        next: { revalidate: 0 },
      }).then((r) => r.json()),
    );

    const articles = await Promise.all(fetches);

    const cleaned = articles.map((a) => ({
      id: a.pageid,
      title: a.title,
      extract: a.extract,
      thumbnail: a.thumbnail?.source ?? null,
      url:
        a.content_urls?.desktop?.page ??
        `https://en.wikipedia.org/wiki/${encodeURIComponent(a.title)}`,
      description: categorize(a.title, a.description ?? null),
    }));

    return NextResponse.json({ articles: cleaned });
  } catch (err) {
    console.error(err);
    return NextResponse.json({ error: "Failed to fetch articles" }, { status: 500 });
  }
}
